kumuluzee:
  datasources:
    - jndi-name: jdbc/KatalogDogodkovDS
      connection-url: jdbc:postgresql://localhost:5432/dogodki
      username: postgres
      password: postgres
      max-pool-size: 20