apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: katalog-dogodkov-deployment
  labels:
    app: katalog-dogodkov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katalog-dogodkov
  template:
    metadata:
      labels:
        app: katalog-dogodkov
    spec:
      containers:
        - image: db8913/katalog_dogodkov:latest
          name: katalog-dogodkov
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_JDBC
              value: "jdbc:postgresql://ec2-54-243-211-197.compute-1.amazonaws.com:5432/d1h0i1446t0fgl?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory"
            - name: POSTGRES_USERNAME
              value: "mszebuqcfupcuy"
            - name: POSTGRES_PASSWORD
              value: "eb5792dd981c2456f30c6f154d5327015c74126efda5041377ad8f070e717663"
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: cluster
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3


---

apiVersion: v1
kind: Service
metadata:
  name: katalog-dogodkov-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30010
  selector:
    app: katalog-dogodkov