kumuluzee:
  name: katalog_dogodkov-service
  version: 1.0.0
  env:
    name: dev

  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379

  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15

  datasources:
    - jndi-name: jdbc/KatalogDogodkovDS
      connection-url: ${POSTGRES_JDBC}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      max-pool-size: 20

  health:
      servlet:
        mapping: /health
        enabled: true
      logs:
        enabled: true
        level: INFO
        period-s: 30
      checks:
        data-source-health-check:
          jndi-name: jdbc/KatalogDogodkovDS
          username: ${POSTGRES_USERNAME}
          password: ${POSTGRES_PASSWORD}
        disk-space-health-check:
          threshold: 100000000
        http-health-check:
          - connection-url: http://localhost:8080/v1/katalog_dogodkov

  metrics:
      web-instrumentation:
        - name: metricsEndpoint
          url-pattern: /metrics/*
        - name: katalogDogodkovEndpoint
          url-pattern: /v1/katalog_dogodkov/*