kumuluzee:
  name: katalog_dogodkov-service
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  datasources:
    - jndi-name: jdbc/KatalogDogodkovDS
      connection-url: jdbc:postgresql://ec2-54-243-211-197.compute-1.amazonaws.com:5432/d1h0i1446t0fgl?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      max-pool-size: 20