kumuluzee:
  name: katalog_dogodkov-service
  version: 1.0.0
  env:
    name: dev

  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://etcd:2379

  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 20
    ping-interval: 15

  datasources:
    - jndi-name: jdbc/KatalogDogodkovDS
      connection-url: ${POSTGRES_JDBC}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      max-pool-size: 20

  health:
      servlet:
        mapping: /health
        enabled: true
      logs:
        enabled: true
        level: INFO
        period-s: 30
      checks:
        data-source-health-check:
          jndi-name: jdbc/KatalogDogodkovDS
          username: ${POSTGRES_USERNAME}
          password: ${POSTGRES_PASSWORD}
        disk-space-health-check:
          threshold: 100000000

  metrics:
      web-instrumentation:
        - name: metricsEndpoint
          url-pattern: /metrics/*
        - name: katalogDogodkovEndpoint
          url-pattern: /v1/katalog_dogodkov/*

  logs:
      config-file-location: /Users/domenb/Desktop/Faks/RSO/vaje/RSO vaje/katalog_dogodkov/src/main/resources/log4j2.xml

rest-properties:
  healthy: true